theme: jekyll-theme-slate
title: BiG CZ
description: The BiG CZ Data Software System
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
githublink_url: "https://github.com/BiG-CZ" 
contact_name: "Anthony Aufdenkampe, Ph.D."
contact_email: "aaufdenkampe@limno.com"